Feature/ui
yaairfernando/BookStore pull request #5
Opened 2020-05-27 21:55 UTC by Dandush03

Finished Setting up the UI

2020-05-28 01:39 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

You have done the basic, we just need to little more styling 🙏 so that your design can look almost the same as the project spec given:
But please Guys, we have strict guidelines as well to follow and one of the requirements is seeing into it that students replicated requirements.

If many students do this, we'll gradually shift away from the requirement from team to team.

Your design is ok, just not requirement-compliant, please try to adhere.THANKS
That's just why you don't get a thumbs up now.......

![image](https://user-images.githubusercontent.com/31897434/83088151-dc4a2880-a08a-11ea-8422-d65585bdf1bb.png)

![image](https://user-images.githubusercontent.com/31897434/80047697-0c3f6280-8506-11ea-9416-a4f1800e2329.png)


**Let's work on the following:**
1. The header (Use similar font and color and add the text `book` and `category`, having the icon at the rightmost part would be nice too)
2. The button to add new book should be text `add book`
3. Users should not be able to add an empty book

**Also, check out my comment below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**

2020-05-28 01:39 UTC, bellom commented on src/styles/styles.scss
> +          outline: none;
You should add `cursor: pointer` so that user can easily see when the button is clicked

2020-05-28 01:39 UTC, bellom commented on src/styles/styles.scss
> +      border: none;
You should add `cursor: pointer` so that user can easily see when the button is clicked

2020-05-28 01:39 UTC, bellom commented on src/containers/BooksForm.jsx
> +          <button type="submit">Add Button</button>
I guess this should be `add book` right
Users should not be able to add an empty book.

![image](https://user-images.githubusercontent.com/31897434/83088028-8f665200-a08a-11ea-85a8-17200090c521.png)

2020-05-29 22:57 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED 

Hi @Dandush03 @YairFernando67  good job working on this, this is coming along very well and it looks elegant too :+1:  

![see this](https://user-images.githubusercontent.com/31897434/80047697-0c3f6280-8506-11ea-9416-a4f1800e2329.png)
the Delete button should be made to look like the "update progress" button in the above screenshot and kept in that position too, this would look super elegant :slightly_smiling_face:  

Please make changes and request for another review :+1: 

**RAPHAEL NORIODE** :mask:

2020-06-01 16:25 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/83430014-dc507c80-a42c-11ea-950b-d5ae31774832.jpg)

### GOOD TO GO.....

2020-06-02 15:16 UTC, merged